gsb_platform_homepage:
    path:     /
    defaults: { _controller: GSBPlatformBundle:Default:index }

gsb_platform_visites_all:
    path:     /rapportVisite/visites
    defaults: { _controller: GSBPlatformBundle:Default:allVisites }

gsb_platform_visites_one:
    path:     /rapportVisite/visite/{id}
    defaults: { _controller: GSBPlatformBundle:Default:selectedVisite }
#    ToDo : requirements : id -> nombre

gsb_platform_visites_add:
    path:     /rapportVisite/add
    defaults: { _controller: GSBPlatformBundle:Default:addVisite }