gsb_platform_homepage:
    path:     /
    defaults: { _controller: GSBPlatformBundle:Default:index }

gsb_platform_visites_all:
    path:     /rapportVisite/visites
    defaults: { _controller: GSBPlatformBundle:Default:allVisites }

gsb_platform_visites_one:
    path:     /rapportVisite/visite/{id}
    defaults: { _controller: GSBPlatformBundle:Default:selectedVisite }


gsb_platform_visites_add:
    path:     /rapportVisite/add
    defaults: { _controller: GSBPlatformBundle:Default:addVisite }

gsb_platform_visites_edit:
    path:     /rapportVisite/edit/{id}
    defaults: { _controller: GSBPlatformBundle:Default:editVisite }

gsb_platform_visites_delete:
    path:     /rapportVisite/delete/{id}
    defaults: { _controller: GSBPlatformBundle:Default:deleteVisite }


  #    ToDo : requirements : id -> nombre
